package com.krycha.vaadin.example.gui.elements.menu;

import java.util.ArrayList;
import java.util.List;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.VerticalLayout;

public class Menu extends CustomComponent implements ClickListener {

	private static final long serialVersionUID = -8942175851931814500L;
	private static final String SELECTED_STYLE = "selected";
	private static final String UNSELECTED_STYLE = "unselected";
	List<MenuEvent> menuEvents = new ArrayList<MenuEvent>();

	private Button active;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public Menu() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		buildMenu();
	}

	private void buildMenu() {
		for (MenuElement menu : MenuElement.values()) {
			MenuButton item = new MenuButton(menu);
			item.setCaption(menu.getItemName());
			item.addClickListener(this);
			item.addStyleName(UNSELECTED_STYLE);
			mainLayout.addComponent(item);
		}
	}

	public void addMenuListener(MenuEvent event) {
		menuEvents.add(event);
	}

	@Override
	public void buttonClick(ClickEvent event) {

		if (active == event.getButton()) {
			return;
		}

		if (active != null) {
			active.removeStyleName(SELECTED_STYLE);
			active.addStyleName(UNSELECTED_STYLE);
		}
		active = event.getButton();
		active.removeStyleName(UNSELECTED_STYLE);
		active.addStyleName(SELECTED_STYLE);

		for (MenuEvent menuEvent : menuEvents) {
			menuEvent.menuClick(((MenuButton)active).getMenuElement());
		}
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		return mainLayout;
	}

}
