package com.krycha.vaadin.example.gui.elements;

import java.util.HashMap;
import java.util.Map;

import org.vaadin.jouni.animator.AnimatorProxy;
import org.vaadin.jouni.animator.AnimatorProxy.Animation;
import org.vaadin.jouni.animator.AnimatorProxy.AnimationEvent;
import org.vaadin.jouni.animator.AnimatorProxy.AnimationListener;
import org.vaadin.jouni.animator.shared.AnimType;

import com.krycha.vaadin.example.gui.elements.content.WelcomeView;
import com.krycha.vaadin.example.gui.elements.menu.Menu;
import com.krycha.vaadin.example.gui.elements.menu.MenuElement;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.navigator.View;
import com.vaadin.navigator.ViewChangeListener.ViewChangeEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.ui.VerticalLayout;

public class Content extends CustomComponent implements View {

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Panel panel;
	@AutoGenerated
	private VerticalLayout verticalPanelLayout;
	@AutoGenerated
	private Menu menu;
	private static final long serialVersionUID = 3883694986681550326L;
	private static final String DEFAULT_NAV = "default";
	private Map<String, CustomComponent> menuViews = new HashMap<String, CustomComponent>();
	private AnimatorProxy proxy = new AnimatorProxy();

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */
	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public Content() {
		buildMainLayout();
		setCompositionRoot(mainLayout);
		mainLayout.addComponent(proxy);
		menuViews.put(DEFAULT_NAV, new WelcomeView());
		for (MenuElement menu : MenuElement.values()) {
			try {
				menuViews.put(menu.getItemName(), (CustomComponent) menu
						.getItemClass().newInstance());
			} catch (InstantiationException e) {
				throw new IllegalArgumentException(e);
			} catch (IllegalAccessException e) {
				throw new IllegalArgumentException(e);
			}
		}
	}

	@Override
	public void enter(ViewChangeEvent event) {


		if (event.getParameters() == null || event.getParameters().isEmpty()) {
			panel.setContent(menuViews.get(DEFAULT_NAV));
			return;
		}

		final String viewItem = event.getParameters();
		if (menuViews.containsKey(viewItem)) {
			final Animation a = proxy.animate(panel, AnimType.FADE_OUT).setDuration(100).setDelay(10);
			proxy.addListener(new AnimationListener() {
				@Override
				public void onAnimation(AnimationEvent event) {
					if (event.getAnimation() == a) {
						panel.setContent(menuViews.get(viewItem));
						proxy.animate(panel, AnimType.FADE_IN).setDuration(100).setDelay(10);
						proxy.removeListener(this);
					}
				}
			});
		}

		if (getMenu().isNotSelected()) {
			getMenu().buttonClick(viewItem);
		}
	}

	public Menu getMenu() {
		return menu;
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(true);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");

		// menu
		menu = new Menu();
		menu.setImmediate(false);
		menu.setWidth("-1px");
		menu.setHeight("-1px");
		mainLayout.addComponent(menu);

		// panel
		panel = buildPanel();
		mainLayout.addComponent(panel);
		mainLayout.setExpandRatio(panel, 1.0f);

		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel() {
		// common part: create layout
		panel = new Panel();
		panel.setImmediate(false);
		panel.setWidth("100.0%");
		panel.setHeight("100.0%");

		// verticalPanelLayout
		verticalPanelLayout = new VerticalLayout();
		verticalPanelLayout.setImmediate(false);
		verticalPanelLayout.setWidth("100.0%");
		verticalPanelLayout.setHeight("100.0%");
		verticalPanelLayout.setMargin(false);
		panel.setContent(verticalPanelLayout);

		return panel;
	}
}
