package com.krycha.vaadin.example.gui.elements;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.server.ExternalResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Link;
import com.vaadin.ui.themes.Reindeer;

public class Footer extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Link mailto;
	@AutoGenerated
	private Label madeBy;
	private static final long serialVersionUID = 4103993851226532820L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Footer() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		mailto.setResource(new ExternalResource("mailto:rkrysinski@gmail.com?subject=KPI%20Tool"));
		mailto.addStyleName(Reindeer.LABEL_H2);
		madeBy.addStyleName(Reindeer.LABEL_H2);

	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");

		// madeBy
		madeBy = new Label();
		madeBy.setImmediate(false);
		madeBy.setWidth("-1px");
		madeBy.setHeight("-1px");
		madeBy.setValue("Made by: ");
		mainLayout.addComponent(madeBy);
		mainLayout.setComponentAlignment(madeBy, new Alignment(6));

		// mailto
		mailto = new Link();
		mailto.setCaption("Roman Krysinski");
		mailto.setImmediate(false);
		mailto.setWidth("-1px");
		mailto.setHeight("-1px");
		mainLayout.addComponent(mailto);

		return mainLayout;
	}

}
