package com.krycha.vaadin.example.gui.elements;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.themes.Reindeer;

public class Header extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private HorizontalLayout mainLayout;
	@AutoGenerated
	private Label headerLabel;
	private static final long serialVersionUID = -9146079595482387345L;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public Header() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		headerLabel.addStyleName(Reindeer.LABEL_H1);
	}

	@AutoGenerated
	private HorizontalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new HorizontalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("-1px");
		mainLayout.setMargin(true);
		
		// top-level component properties
		setWidth("100.0%");
		setHeight("-1px");
		
		// headerLabel
		headerLabel = new Label();
		headerLabel.setImmediate(false);
		headerLabel.setWidth("100.0%");
		headerLabel.setHeight("-1px");
		headerLabel
				.setValue("Welcome in demo tool for collecting Customer Measurements");
		mainLayout.addComponent(headerLabel);
		mainLayout.setComponentAlignment(headerLabel, new Alignment(24));
		
		return mainLayout;
	}

}
